---

- name: install mongodb
  apt:
    update_cache: yes
    name: mongodb
    state: present

- name: Configure service supervisor
  systemd:
    name: mongodb
    enabled: yes
    state: started
  tags: install
